swagger: "2.0"
info:
  title: "Your API"
  description: "API to manage a mechanic shop"
  version: "1.0.0"
host: "project-advanced-api-development.onrender.com"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"

responses:
  UnauthorizedError:
    description: "Unauthorized - Token is missing or invalid"
    schema:
      type: object
      properties:
        message:
          type: string
    examples:
      application/json:
        case1:
          message: "Invalid token!"
        case2:
          message: "Token has expired!"
        case3:
          message: "Token is no longer valid"
        case4:
          message: "Invalid role in token"
        case5:
          message: "Authorization header must start with 'Bearer'"
        case6:
          message: "Bearer token missing after prefix"
        case7:
          message: "Authorization header missing"

securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: "Enter your token like: Bearer <token>"

definitions:
  LoginCredentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password

  LoginResponse:
    type: object
    properties:
      token:
        type: string
      message:
        type: string
      status:
        type: string

  Mechanic:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      phone:
        type: string
      role:
        type: string
      user_uuid:
        type: string
      token_version:
        type: integer
      salary:
        type: integer
      password:
        type: string

  AllMechanicsResponse:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
        password:
          type: string
        phone:
          type: string
        salary:
          type: integer
        user_uuid:
          type: string
        token_version:
          type: integer

  ServiceTicketsResponse:
    type: "object"
    properties:
      id:
        type: "integer"
      customer_id:
        type: "integer"
      inventory_links:
        type: "array"
        items:
          type: object
          properties:
            inventory_id:
              type: integer
            quantity_used:
              type: integer
            quantity_returned:
              type: integer
      mechanics:
        type: "array"
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
      VIN:
        type: "string"
      service_date:
        type: "string"
        format: "date"
      service_desc:
        type: "string"

  Customer:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      phone:
        type: string
      password:
        type: string
      role:
        type: string
        example: customer
      token_version:
        type: integer
      user_uuid:
        type: string

  CreateCustomerPayload:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      phone:
        type: string
      password:
        type: string
    required:
      - name
      - email
      - phone
      - password

  CreateCustomerResponse:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      phone:
        type: string
      password:
        type: string
      role:
        type: string
        example: customer
      token_version:
        type: integer
      user_uuid:
        type: string

  AllCustomersResponse:
    type: object
    properties:
      total:
        type: integer
      page:
        type: integer
      pages:
        type: integer
      per_page:
        type: integer
      customers:
        type: array
        items:
          $ref: "#/definitions/Customer"

  UpdateCustomerPayload:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"

  UpdateCustomerResponse:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      password:
        type: "string"
      role:
        type: string
        example: customer
      token_version:
        type: integer
      user_uuid:
        type: string

  DeleteCustomerResponse:
    type: "object"
    properties:
      message:
        type: "string"

paths:
  /customers/login:
    $ref: "./customers.yaml#/paths/~1customers~1login"
  /customers:
    $ref: "./customers.yaml#/paths/~1customers"
  /customers/{customer_id}:
    $ref: "./customers.yaml#/paths/~1customers~1{customer_id}"
  /customers/my-tickets:
    $ref: "./customers.yaml#/paths/~1customers~1my-tickets"

  /mechanics/login:
    $ref: "./mechanics.yaml#/paths/~1mechanics~1login"
  /mechanics:
    $ref: "./mechanics.yaml#/paths/~1mechanics"
  /mechanics/{mechanic_id}:
    $ref: "./mechanics.yaml#/paths/~1mechanics~1{mechanic_id}"
  /mechanics/my-tickets:
    $ref: "./mechanics.yaml#/paths/~1mechanics~1my-tickets"

  /service_tickets:
    $ref: "./service_tickets.yaml#/paths/~1service_tickets"
  /service_tickets/most-tickets:
    $ref: "./service_tickets.yaml#/paths/~1service_tickets~1most-tickets"
  /service_tickets/{ticket_id}:
    $ref: "./service_tickets.yaml#/paths/~1service_tickets~1{ticket_id}"
  /service_tickets/{ticket_id}/update-info:
    $ref: "./service_tickets.yaml#/paths/~1service_tickets~1{ticket_id}~1update-info"
  /service_tickets/{ticket_id}/update-mechanics:
    $ref: "./service_tickets.yaml#/paths/~1service_tickets~1{ticket_id}~1update-mechanics"
  /service_tickets/{ticket_id}/update-parts:
    $ref: "./service_tickets.yaml#/paths/~1service_tickets~1{ticket_id}~1update-parts"

  /inventories:
    $ref: "./inventories.yaml#/paths/~1inventories"
  /inventories/{part_id}:
    $ref: "./inventories.yaml#/paths/~1inventories~1{part_id}"
